### ISSUE TITLE
[META] Replace buefy with Vocabulary

### ISSUE THREAD

**Issue by obulat** [creativecommons/chooser#229]
## Description

This Meta issue will track the transition from buefy to Vocabulary, the CreativeCommons design system. The following components need to be replaced: 
- [x] radio: [issue#223](https://github.com/creativecommons/chooser/issues/223)
- [x] checkbox: [issue#223](https://github.com/creativecommons/chooser/issues/223)
- [x] input field (text and textarea): [issue#224](https://github.com/creativecommons/chooser/issues/224)
- [x] buttons: [issue#222](https://github.com/creativecommons/chooser/issues/222)
- [x] tabs: [issue#225](https://github.com/creativecommons/chooser/issues/225)
- [x] modal: [issue#226](https://github.com/creativecommons/chooser/issues/226)
- [x] select: [issue#227](https://github.com/creativecommons/chooser/issues/227)
- [x] icons (Fontawesome icons also need to be replaced with Vocabulary icons): [issue#228](https://github.com/creativecommons/chooser/issues/228)

The locale will be inside the site header, so the locale will need to be removed from the Chooser itself.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by koolgax99** [comment]
can i work on this issue?

**Comment by Cronus1007** [comment]
@obulat Any updates regarding this issue.

**Comment by obulat** [comment]
As you can see from the checkboxes, all but one of the linked issued have been solved. The remaining issue has a  PR which needs a review, so this issue is not open for contribution.

**Comment by obulat** [comment]
All the PRs have been merged, closing this issue.
