### ISSUE TITLE
Upgrade project dependencies

### ISSUE THREAD

**Issue by brylie** [creativecommons/chooser#355]
When installing the project via `npm install` there are several notices for outdated/insecure dependencies (some of which only affect the development environment.)

## Reproduction

1. clone the project
2. run `npm install`
3. See warnings

## Expectation

The project should strive to keep dependencies up-to-date. In effect, this should probably be routine, but is worth earmarking as an issue for now.

## Task

- [ ] review dependencies in `package.json`
- [ ] remove any `dependencies` or `devDependencies` that are unneeded or no longer in use
- [ ] upgrade as many remaining dependencies as possible to the latest compatible versions
- [ ] document which dependencies were not updated and the reasons, such as breaking changes or incompatibility

**Comment by brylie** [comment]
Now that the Chooser dependencies are cleaned up, we should have more success with this issue.
