### ISSUE TITLE
Consider deprecating stand-alone build

### ISSUE THREAD

**Issue by brylie** [creativecommons/chooser#385]
The project currently includes page elements, such as a header and footer, that are intended for a stand-alone build. Since we are moving towards publishing Chooser as a web component, the intention of the project is for Chooser to be embedded in other pages/projects by default. Hence, there may no longer be a need for a stand-alone build. 

Note: This task is contingent on our ability to embed the Chooser in the new creativecommons.org redesign with a Gutenberg HTML block.

## Task

If we go forward with this idea, the following steps would be applicable.

- [ ] remove all non-chooser components from the project
    - [ ] header
    - [ ] breadcrumb
    - [ ] chooser
- [ ] remove any conditional code for building the project in "embedded" mode
- [ ] update docs accordingly
- [ ] update npm scripts accordingly

**Comment by brylie** [comment]
This issue may resolve #384

**Comment by MdSahil-oss** [comment]
@TimidRobot is this issue still to be resolved, If so then I would like to work on this.

**Comment by TimidRobot** [comment]
@MdSahil-oss oops, this issue is a little outdated. I updated the tags (🚧 **status: blocked**)
