### ISSUE TITLE
Audit code and reduce build size

### ISSUE THREAD

**Issue by brylie** [creativecommons/chooser#386]
While building the Chooser as a component, there are several asset size limit warnings, such as the following:

>  warning  
>
> asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
> This can impact web performance.
> Assets: 
>      license-chooser.min.js (1.75 MiB)

>  warning  
>
> entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
> Entrypoints:
>  license-chooser (2.51 MiB)
>      license-chooser.js

## Task

- [ ] audit the chooser codebase to look for any code or dependencies that can be removed to reduce the bundle size
- [ ] determine if an alternative project configuration, such as tree-shaking, might be implemented to reduce bundle size
- [ ] discuss findings to determine which changes to make
- [ ] make desired changes to reduce bundle size

**Comment by DanielGraham123** [comment]
Hello @brylie, I'm working on this issue...

**Comment by PeaceOffiong** [comment]
I will be working on this issue

**Comment by JeffyDave** [comment]
Hi @PeaceOffiong , I would love to assist you in working on this if you do not mind.

**Comment by Cronus1007** [comment]
@possumbilities @TimidRobot Shall I pick up this issue?

**Comment by possumbilities** [comment]
@Cronus1007 feel free to tackle it, and thankyou! ❤️

**Comment by Cronus1007** [comment]
@possumbilities Unused dependencies which I was able to find are

1. bulma 
2. core-js
3. sass
4. clipboardy 
5. eslint-plugin-prettier

While running `npm run build-component` it gives
>  warning  
>
> asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
> This can impact web performance.
> Assets: 
>      license-chooser.min.js (1.25 MiB)

>  warning  
>
> entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
> Entrypoints:
>  license-chooser (1.79 MiB)
>      license-chooser.js

**Comment by possumbilities** [comment]
@Cronus1007 I could be wrong, but could you provide more info. It seems like several of those are in use in the dependency chain somewhere.

I thought `clipboardy` was how the clipboard copy works within the Chooser. I thought the `sass` and `bulma` dependencies are necessary for the app/site since it's utilizing Vocabulary.

The other two I'm not sure on. Is there some kind of output or report indicating that they are indeed not used at all?

**Comment by possumbilities** [comment]
@Cronus1007 that's a good idea, I'm happy to test the branch

**Comment by Cronus1007** [comment]
@possumbilities  Sure I am on it.
